// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import path from "path";

// Load correct env file based on NODE_ENV
const NODE_ENV = process.env.NODE_ENV || "development";

const envFileMap: Record<string, string> = {
  development: ".env.development",
  test: ".env.test",
  production: ".env.production",
};

// Manually load the env file BEFORE Prisma reads env()
require("dotenv").config({
  path: path.resolve(process.cwd(), envFileMap[NODE_ENV]),
});

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "ts-node ./prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
